#!/bin/bash

# Demo script showing how to use the Explain Error Plugin

echo "=== Explain Error Plugin Demo ==="
echo ""
echo "This plugin provides two ways to get AI explanations for build failures:"
echo ""
echo "1. PIPELINE STEP METHOD:"
echo "   Add explainError() step to your pipeline:"
echo ""
echo "   pipeline {"
echo "       agent any"
echo "       stages {"
echo "           stage('Build') {"
echo "               steps {"
echo "                   sh 'make build'"
echo "               }"
echo "           }"
echo "       }"
echo "       post {"
echo "           failure {"
echo "               script {"
echo "                   explainError()"
echo "               }"
echo "           }"
echo "       }"
echo "   }"
echo ""
echo "2. CONSOLE OUTPUT BUTTON METHOD:"
echo "   - Go to any build's console output page"
echo "   - Click the 'Explain Error' button above the console output"
echo "   - The AI will analyze the entire console output"
echo "   - Results appear below the button"
echo ""
echo "CONFIGURATION:"
echo "1. Go to Jenkins > Manage Jenkins > Configure System"
echo "2. Find 'Explain Error Plugin' section"
echo "3. Set your OpenAI API key"
echo "4. Optionally configure API URL and model"
echo ""
echo "Plugin file: target/explain-error-plugin.hpi"
echo "Size: $(du -h target/explain-error-plugin.hpi | cut -f1)"
echo ""
echo "Ready to install in Jenkins!"
